
include_recipe 'base::hack_dnf'
include_recipe 'base::firewall'
include_recipe 'base::docker'
include_recipe 'base::locale'
include_recipe 'base::me'
include_recipe 'base::packages'
include_recipe 'base::vim'
include_recipe 'base::python'
include_recipe 'base::ruby'
