
include_recipe 'robin-desktop::hack_dnf'
include_recipe 'robin-desktop::locale'
include_recipe 'robin-desktop::docker'
include_recipe 'robin-desktop::me'
include_recipe 'robin-desktop::packages'
include_recipe 'robin-desktop::xwindows'
include_recipe 'robin-desktop::fonts'
include_recipe 'robin-desktop::setup_chef'
include_recipe 'robin-desktop::sublime'
include_recipe 'robin-desktop::vim'
include_recipe 'robin-desktop::chrome'
include_recipe 'robin-desktop::vpn'
include_recipe 'robin-desktop::python'
