name 'workstation'
maintainer 'Robin Ridler'
maintainer_email 'robin.ridler@gmail.com'
license 'all_rights'
description 'Installs/Configures desktop'
long_description 'Installs/Configures desktop'
version '0.1.0'

depends 'yum'
depends 'vagrant', '= 0.3.0'
depends 'firewall', '~> 2.0.5'
